#!/usr/bin/env bash
set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
BRANCH=${VALIDATED_BRANCH:-validated-xeon6}
PUB=$(mktemp -d)
trap 'git -C "$ROOT" worktree remove --force "$PUB" >/dev/null 2>&1 || true; rm -rf "$PUB"' EXIT

if [[ ! -f "$ROOT/results/weekly-summary.json" || ! -f "$ROOT/results/weekly-summary.html" ]]; then
  echo "No weekly summary was generated; skipping catalog publication" >&2
  exit 0
fi

mkdir -p "$ROOT/latest"
cp "$ROOT/results/weekly-summary.json" "$ROOT/latest/xeon6-validation.json"
cp "$ROOT/results/weekly-summary.html" "$ROOT/latest/xeon6-validation.html"
cp "$ROOT/results/discovery.json" "$ROOT/latest/xeon6-discovery.json"
cp "$ROOT/results/run-metadata.json" "$ROOT/latest/run-metadata.json"

HISTORY_REL=$(python3 - "$ROOT/results/run-metadata.json" <<'PY'
import json
import sys
from pathlib import Path

print(json.loads(Path(sys.argv[1]).read_text())["history_path"])
PY
)

if [[ -z "$HISTORY_REL" || "$HISTORY_REL" != history/* ]]; then
  echo "Invalid history path: $HISTORY_REL" >&2
  exit 2
fi
if [[ ! -d "$ROOT/$HISTORY_REL" ]]; then
  echo "Current run history directory does not exist: $ROOT/$HISTORY_REL" >&2
  exit 2
fi

if git -C "$ROOT" show-ref --verify --quiet "refs/remotes/origin/$BRANCH"; then
  git -C "$ROOT" worktree add -B "$BRANCH" "$PUB" "origin/$BRANCH"
else
  # Use the current checkout as a temporary base, then replace it with a clean
  # orphan publication tree.
  git -C "$ROOT" worktree add --detach "$PUB" HEAD
  git -C "$PUB" checkout --orphan "$BRANCH"
  git -C "$PUB" rm -rf . >/dev/null 2>&1 || true
fi

# validated/ and latest/ are snapshots. history/ is append-only by run ID, so
# previous reports remain available on the same publication branch.
rm -rf "$PUB/validated" "$PUB/latest"
cp -a "$ROOT/validated" "$PUB/validated"
cp -a "$ROOT/latest" "$PUB/latest"
mkdir -p "$PUB/$(dirname "$HISTORY_REL")"
rm -rf "$PUB/$HISTORY_REL"
cp -a "$ROOT/$HISTORY_REL" "$PUB/$HISTORY_REL"

cat > "$PUB/README.md" <<'EOM'
# Xeon 6 validated vLLM recipe outputs

This branch is generated by a Xeon 6 validation workflow. A separate branch
is not created for every run.

- `validated/xeon6/<org>/<model>/` contains the latest known-good generated
  `config.yml`, `env.sh`, recipe rendering, validation metadata, and run notes.
- `latest/xeon6-validation.html` and `.json` contain the newest run summary.
- `history/YYYY-MM-DD/run-<number>-attempt-<attempt>/` preserves each run's
  HTML/JSON summary, discovery/system/image metadata, and per-model evidence.
- A failed candidate does not replace the previous validated model bundle, but
  its run evidence remains in `history/`.
EOM

git -C "$PUB" add README.md validated latest history
if git -C "$PUB" diff --cached --quiet; then
  echo "No validated catalog or history changes to publish"
  exit 0
fi

git -C "$PUB" -c user.name='Xeon Recipe Validation Bot' \
  -c user.email='xeon-recipe-validation@users.noreply.github.com' \
  commit -m "Update Xeon 6 validation ${VALIDATION_RUN_ID:-run}"
git -C "$PUB" push origin "HEAD:$BRANCH"
echo "Published validated catalog and $HISTORY_REL to $BRANCH"
